import "./globals.css";
import { Inter } from "next/font/google";
import AuthSession from "./ui/components/authSession";

import Avatar from "./ui/components/avatar";
import { TabGroup } from "./ui/components/tab-group";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <AuthSession>
          <div className="py-10 px-10 h-screen">
            <div className="flex  justify-between text-white">
              <TabGroup
                path=""
                items={[
                  {
                    text: "Home",
                  },
                  {
                    text: "Users",
                    slug: "users",
                    segment: "users",
                  },
                ]}
              />
              <Avatar />
            </div>
            <main className="mt-10">{children}</main>
          </div>
        </AuthSession>
      </body>
    </html>
  );
}
