import "./globals.css";
import { Inter } from "next/font/google";
import { TabGroup } from "./ui/components/tab-group";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <div className="py-10 px-10 h-screen">
          <div className="flex space-x-5 text-white">
            <TabGroup
              path=""
              items={[
                {
                  text: "Home",
                },
                {
                  text: "Users",
                  slug: "users",
                  segment: "users",
                },
                {
                  text: "Text",
                  slug: "text",
                  segment: "text",
                },
              ]}
            />
          </div>
          <div className="mt-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
