import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto py-10 px-10 h-screen">
          <div className="flex space-x-5">
            <Link href={"/"} as={"/"}>
              Home
            </Link>
            <Link href={"/users"} as={"/users"}>
              Users
            </Link>
          </div>
          <div className="mt-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
